services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_TELEMETRY_DISABLED: 1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    profiles: ["dev"]
    command: npm run dev  # Use development mode instead of production
